version: '3.0'
services:
  web:
    image: nugrohop2003/blogx:${GIT_COMMIT_SHORT}
    ports:
      - 8000:8000
    volumes:
      - ./.env.example:/blogx/.env
    command: 'php artisan serve --host=0.0.0.0'
